### ISSUE TITLE
Rewrite the site index.html page

### ISSUE THREAD

**Issue by crxssed7** [crxssed7/ourworld#1]
The current text doesn't make much sense and isn't professional.

**Comment by nordic16** [comment]
The `index.html` text should be moved to a future about or FAQ page. It doesn't have to be _that_ professional though.

**Comment by crxssed7** [comment]
We won't need an FAQ page as there won't be many questions that need to be answered. We can add the about section on the `index.html` page as that's what I was referring to anyway.
