### ISSUE TITLE
Write an explanation as to what a geological timescale is

### ISSUE THREAD

**Issue by crxssed7** [crxssed7/ourworld#2]
Need to identify what they are, does not need to be too detailed as each timescale will have its own description

**Comment by nordic16** [comment]
I'll give it a try

**Comment by nordic16** [comment]
I'm done with the 4 main Eons. Will write about the geological Eras from the Phanerozoic soon.

**Comment by crxssed7** [comment]
> I'm done with the 4 main Eons. Will write about the geological Eras from the Phanerozoic soon.

This issue refers more to an explanation of what a timescale is not about *each* timescale: https://github.com/crxssed7/ourworld/blob/master/timescales/templates/timescales/index.html#L16
So a summary of what a timescale is that can go on the /timescales/ page.

We will need to at some point actually write about each timescale, but we can do that once we have deployed the project and the database is live (if you want you can carry on writing about each timescale whenever you want, but you don't *need* to just yet).

**Comment by crxssed7** [comment]
I should've been a bit more clear lol
